version: '3.7'

services:
  dockerapidemo:
    image: ${DOCKER_REGISTRY-}dockerapidemo
    ports:
      - "5000:80"
    env_file:
      - ./DockerAPIDemo/.env
    build:
      context: .
      dockerfile: DockerAPIDemo/Dockerfile
